services:
  postgres:
    image: postgres:16-alpine
    container_name: churn_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: churn_user
      POSTGRES_PASSWORD: churn_pass
      POSTGRES_DB: churn_db
    ports:
      - "5432:5432"
    volumes:
      - churn_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U churn_user -d churn_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  churn_pg_data:
